name: build

on:
  workflow_call:
    inputs:
      scan:
        type: boolean
        default: false
      pack:
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      scan:
        type: boolean
        default: false
      pack:
        type: boolean
        default: false

jobs:
  format:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Check formatting
        uses: jidicula/clang-format-action@v4.18.0
        with:
          clang-format-version: '18'
          check-path: '.'
          exclude-regex: 'build'

  scan:
    if: inputs.scan

    needs: [format]

    runs-on: ubuntu-24.04-arm

    container:
      image: joinframework/join-ci:latest

    permissions:
      contents: read
      security-events: write

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Initialize codeql
        uses: github/codeql-action/init@v4.34.1
        with:
          languages: cpp

      - name: Configure
        run: cmake --preset gcc-debug

      - name: Build
        run: cmake --build --preset gcc-debug

      - name: Run codeql scan
        uses: github/codeql-action/analyze@v4.34.1

  build:
    needs: [format]

    runs-on: ubuntu-24.04-arm

    container:
      image: joinframework/join-ci:latest

    permissions:
      contents: read

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Configure (debug)
        run: cmake --preset gcc-debug

      - name: Build (debug)
        run: cmake --build --preset gcc-debug

      - name: Configure (release)
        run: cmake --preset gcc-release -DCMAKE_INSTALL_PREFIX=/usr

      - name: Build (release)
        run: cmake --build --preset gcc-release

      - name: Package
        if: inputs.pack
        run: |
          cd build/gcc-release
          cpack -G DEB

      - name: Upload
        if: inputs.pack
        uses: actions/upload-artifact@v7.0.0
        with:
          name: pifan-package
          path: build/gcc-release/pifan_*.deb