name: cd

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/build.yml

    permissions:
      contents: read

    secrets: inherit

    with:
      pack: true
