name: ci

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/build.yml

    permissions:
      contents: write
      security-events: write

    secrets: inherit
