name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

    permissions:
      contents: write

    secrets: inherit

    with:
      scan: true
      release: true
